version: '3.4'

services:
  products.api:
    image: ${DOCKER_REGISTRY-}products-services
    container_name: products_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__ProductDB=Server=mysql_service;Port=3306;Database=productdb;User=root;Password=123;
      - ASPNETCORE_ENVIRONMENT=Development

  mysql:
    image: mysql:8.0
    container_name: mysql_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: productdb
    ports:
      - "3307:3306"  # Map host port 3307 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
